- name: Update packages
  shell: "apt-get update -y -q && apt-get --enable-upgrade upgrade -y -q"
  ignore_errors: true

- name: apt-get install
  shell: "apt-get install -y adduser libfontconfig1 musl"

- name: Download packages
  shell: "wget https://dl.grafana.com/oss/release/grafana_10.3.1_amd64.deb"

- name: Install grafana
  shell: "dpkg -i grafana_10.3.1_amd64.deb"

- name: Install grafana
  shell: "/bin/systemctl enable grafana-server"

- name: Install grafana
  shell: "/bin/systemctl start grafana-server"