---
# tasks file for node-exporter
- name: Stop service
  command: docker-compose down
  become: true
  args:
    chdir: "{{vm_folder}}/node-exporter"
  ignore_errors: true

- name: Create configs directory
  file:
    path: "{{vm_folder}}/node-exporter/"
    state: directory

- name: Copy compose file for VM exporter
  template:
    src: docker-compose-node-exporter.yml.j2
    dest: "{{vm_folder}}/node-exporter/docker-compose.yml"
    backup: yes
    force: yes

- name: Run service
  command: docker-compose up -d
  become: true
  args:
    chdir: "{{vm_folder}}/node-exporter"